### ISSUE TITLE
npm run server 报错啦

### ISSUE THREAD

**Issue by lizeyun** [zxysilent/blog#11]
$ npm run build
npm ERR! path /usr/local/go/src/blog/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/usr/local/go/src/blog/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-11-05T10_23_52_811Z-debug.log

可以帮忙看看吗

**Comment by lizeyun** [comment]
npm init 生产 package.json 之后，又变成这样了
![image](https://user-images.githubusercontent.com/19726385/98229910-7779ef00-1f95-11eb-9653-b14c0abc20d3.png)

**Comment by zxysilent** [comment]
前端操作，需要去`vue`目录

**Comment by lizeyun** [comment]
谢谢。。
