### ISSUE TITLE
您好，请问下为什么提供的账号密码不对。。

### ISSUE THREAD

**Issue by lizeyun** [zxysilent/blog#12]
如果我想去数据库修改默认密码的话

需要怎么修改 。，使用的mysql passwd() 函数吗？
![image](https://user-images.githubusercontent.com/19726385/98543799-f476d280-22cd-11eb-96fc-f301d951e4d5.png)

**Comment by zxysilent** [comment]
https://github.com/zxysilent/blog/blob/master/vue/.env.production#L1 
这个地方可能要修改你自己的网站
