### ISSUE TITLE
请问 go run main.go 报这个错 怎么处理呀， go小白一个。。。

### ISSUE THREAD

**Issue by hulao6** [zxysilent/blog#14]
请问 go run main.go 报这个错 怎么处理呀， go小白一个。。。

go: github.com/BurntSushi/toml@v0.3.1: Get https://proxy.golang.org/github.com/%21burnt%21sushi/toml/@v/v0.3.1.mod: dial tcp 74.125.203.141:443: connect: connection refused

**Comment by zxysilent** [comment]
需要配置环境变量 `go env -w GOPROXY=https://goproxy.cn,direct`

**Comment by hulao6** [comment]
tks
