### ISSUE TITLE
vue

### ISSUE THREAD

**Issue by bjtuweb-12281047** [zxysilent/blog#19]
npm run serve

> zxysilent-blog@0.2.0 serve
> vue-cli-service serve

 INFO  Starting development server...
98% after emitting SizeLimitsPlugin

 ERROR  Failed to compile with 1 error                                                                                                                                                                         下午11:30:25

 error  in ./src/main.js

Syntax Error: Error: [BABEL] /Users/rongwang/Documents/github/blog/vue/src/main.js: Cannot find module 'core-js/package.json'
Require stack:
- /Users/rongwang/Documents/github/blog/vue/node_modules/@vue/babel-preset-app/index.js
- /Users/rongwang/Documents/github/blog/vue/node_modules/@babel/core/lib/config/files/module-types.js
- /Users/rongwang/Documents/github/blog/vue/node_modules/@babel/core/lib/config/files/configuration.js
- /Users/rongwang/Documents/github/blog/vue/node_modules/@babel/core/lib/config/files/index.js
- /Users/rongwang/Documents/github/blog/vue/node_modules/@babel/core/lib/index.js
- /Users/rongwang/Documents/github/blog/vue/node_modules/@vue/cli-plugin-babel/index.js
- /Users/rongwang/Documents/github/blog/vue/node_modules/@vue/cli-service/lib/Service.js
- /Users/rongwang/Documents/github/blog/vue/node_modules/@vue/cli-service/bin/vue-cli-service.js (While processing: "/Users/rongwang/Documents/github/blog/vue/node_modules/@vue/babel-preset-app/index.js")
    at Generator.next (<anonymous>)
    at Generator.next (<anonymous>)
    at Generator.next (<anonymous>)

 @ multi (webpack)-dev-server/client?http://127.0.0.1:8080/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

**Comment by zxysilent** [comment]
try `npm install` and then `npm run serve`
