### ISSUE TITLE
使用

### ISSUE THREAD

**Issue by ghost** [zxysilent/blog#2]
请问前台地址如何，进入之后默认是后台页面，找不到前台地址

**Comment by zxysilent** [comment]
![image](https://user-images.githubusercontent.com/19162822/58378798-a9c7a480-7fcc-11e9-9ae1-4bcaf842b131.png)


默认就是前台哒 
放到views 下面的

后台是用 vue开发的

**Comment by ghost** [comment]
> 默认就是前台哒
> 放到views 下面的
> 后台是用 vue开发的

我启动了vue项目和go后台，当我访问8080的时候默认是访问的是后台管理界，然后我点击跳转到前台也无响应，请问我该如何访问前台页面呢，后端人员，对前端不是很懂

**Comment by ghost** [comment]
您好，我找到前台入口了，原来您是用了beego框架在服务端嵌入了页面。我还以为前台也是一个前后也是一个独立的系统，这样能彻底实现前后端分离。

**Comment by zxysilent** [comment]
echo  不是 beego 哦
