### ISSUE TITLE
问题多多

### ISSUE THREAD

**Issue by Tine789** [zxysilent/blog#20]
大佬，能出个视频嘛，一天没部署好。问题一：工程放在d盘，go build main.go报错在k盘找不到包（go安装在k盘的原因吗）；问题二：界面还能起来，服务怎么都起不起来，我怀疑是数据库问题，但是我换了其他项目又部署成功了。

**Comment by zxysilent** [comment]
- 确保go环境正常
- 先生成swagger文档
- 编译二进制程序
- 还原数据库
- 修改配置文件
- 启动

**Comment by Tine789** [comment]
后台起来后，用户不存在，但是数据库中有的哇。mysql启了，又好像没有用到，数据库有点懵。![图片](https://github.com/zxysilent/blog/assets/87940618/94a43e76-b2c1-4e98-be34-3e0c7faa0397)
![图片](https://github.com/zxysilent/blog/assets/87940618/6ec2630c-3fe6-43e2-8efe-6a0402ed344e)

**Comment by zxysilent** [comment]
可以看下日志，看是用的MySQL还是sqlite
现在两种数据库都可以

**Comment by Tine789** [comment]
谢谢
