### ISSUE TITLE
前后端分离部署问题，运行命令npm run preview ，登录界面闪过一下，报错：500

### ISSUE THREAD

**Issue by Tine789** [zxysilent/blog#22]
编译后的dist文件复制到blog目录下与后端服务一起编译后能正常运行；前后端分离部署，后端起来后，在vue目录下运行npm run dev，npm run dev-online正常运行。接下来，步骤一：npm run build，步骤二：npm run  preview 报错500，现象及日志截图如下，日志在最后一张图。
vendor-50266303.js
![1](https://github.com/zxysilent/blog/assets/87940618/57fbc9ba-aed9-4a12-a63d-27931236e861)
![2](https://github.com/zxysilent/blog/assets/87940618/4d20506e-54a8-416b-8394-7e9d8c534fff)
![3](https://github.com/zxysilent/blog/assets/87940618/c6539ec4-15c3-4119-862e-f58c25fdfe31)
![4](https://github.com/zxysilent/blog/assets/87940618/eef7e088-18f0-4e4f-a44f-2a50d38e975d)
![5](https://github.com/zxysilent/blog/assets/87940618/1ad12d39-8cca-4240-bc04-9caf52b87adf)
![6](https://github.com/zxysilent/blog/assets/87940618/0dcf28af-52b1-405a-bbcc-45ca4eacf9d6)

**Comment by zxysilent** [comment]
npm run preview 没适配，你直接部署就行
如果是前后端单独部署，需要调整.env.production 里面VITE_APP_SRV 的值，指向你的服务地址
如果是预览 请修改vite.config.ts 第16行，返回你的服务地址

**Comment by Tine789** [comment]
好的，谢谢
