### ISSUE TITLE
build报错

### ISSUE THREAD

**Issue by agxmaster** [zxysilent/blog#4]
master分支的代码
go version go1.13.5 linux/amd64

go build 执行报错

router/dev.go:16:13: cannot use echoSwagger.WrapHandler (type "github.com/labstack/echo/v4".HandlerFunc) as type "github.com/labstack/echo".HandlerFunc in argument to engine.GET

**Comment by zxysilent** [comment]
可能是我没有使用 `go mod ` 的原因 
解决的话 可能需要关闭 mod 或者 github.com/labstack/echo/v4 替换所有的 github.com/labstack/echo

**Comment by zxysilent** [comment]
已经修改为go mod 方式
