### ISSUE TITLE
缺少docs目录代码

### ISSUE THREAD

**Issue by vinsonlou** [zxysilent/blog#7]
缺少docs目录代码

import (
	// docs
	_ "blog/docs"

	"github.com/labstack/echo"
	echoSwagger "github.com/swaggo/echo-swagger"
)

_ "blog/docs"
引用出错，是代码不完整？

**Comment by zxysilent** [comment]
使用 swag init 会自动生成文档目录哦

发自 zxysilent

On Feb 9, 2020, at 04:44, liuhy <notifications@github.com<mailto:notifications@github.com>> wrote:


缺少docs目录代码

import (
// docs
_ "blog/docs"

"github.com/labstack/echo<http://github.com/labstack/echo>"
echoSwagger "github.com/swaggo/echo-swagger<http://github.com/swaggo/echo-swagger>"


)

_ "blog/docs"
引用出错，是代码不完整？

**Comment by PalaChen** [comment]
swag init 这个命令在哪里使用？
