### ISSUE TITLE
API接口文档运行

### ISSUE THREAD

**Issue by NOLouser** [zxysilent/blog#8]
博主，请问API接口文档是要单独起端口运行，才能通过网址访问（即没有集成到后台）？本人刚接触GO，然后对go-swagger不太了解

**Comment by zxysilent** [comment]
1. 安装 swag
```go get -u github.com/swaggo/swag/cmd/swag```
2.运行swag init 生成api文档

访问 127.0.0.1:85/swagger/index.html
就能查看到文档了

**Comment by NOLouser** [comment]
![image](https://user-images.githubusercontent.com/40658641/74587358-5ac71100-502c-11ea-842b-65aea1e889fa.png)
博主，已经看到api文档，但是网页提示错误，这个是版本问题？
其次，我想问下，如果选择模式的prod（即线上运行版本），swagger的api文档默认是关闭的吗？

**Comment by zxysilent** [comment]
一直没用 doc.json 直接在线调试的使用的
prod 模式不会打包api文档的 添加的条件编译那个代码都不会编译进去

**Comment by NOLouser** [comment]
![image](https://user-images.githubusercontent.com/40658641/74603309-05066d80-50ed-11ea-87e6-2df8199f8eaa.png)

博主，访问api文档接口的问题，你有头绪吗？

**Comment by zxysilent** [comment]
修改 [修复文档错误](https://github.com/zxysilent/blog/commit/337e3416b2b99c2239f3055066a99a6fc663b63c)
