### ISSUE TITLE
windows下交叉编译linux下可执行文件

### ISSUE THREAD

**Issue by NOLouser** [zxysilent/blog#9]
![image](https://user-images.githubusercontent.com/40658641/74581025-6cd19100-4fe5-11ea-8360-38c5e95526b8.png)

在windows下交叉编译linux下的可执行文件，我看下报错日志，它为什么会引用成windows下的绝对路径？我怎么感觉这有点像C++的动态链接库一样的

**Comment by zxysilent** [comment]
配置文件，要放到可执行程序的同级目录 conf下面，才能读取到，
具体查看 配置文件路径 https://github.com/zxysilent/blog/blob/master/conf/config.go#L68

**Comment by NOLouser** [comment]
博主，确实是配置文件问题，但是现在又出现了一个问题，请看截图
![image](https://user-images.githubusercontent.com/40658641/74586876-0a998000-5027-11ea-880b-51b41e551993.png)

**Comment by NOLouser** [comment]
![image](https://user-images.githubusercontent.com/40658641/74586905-6b28bd00-5027-11ea-957a-bf2ddef37cd2.png)

![image](https://user-images.githubusercontent.com/40658641/74586891-58ae8380-5027-11ea-8c49-91c81e195844.png)

**Comment by NOLouser** [comment]
博主，不好意思，是自己粗心了，是配置的相对路径不对
